import type { Metadata } from "next";
import { Geist, Geist_Mono, Plaster, Playwrite_DE_Grund_Guides } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const plaster = Plaster({
  variable: "--font-plaster",
  weight: "400",
  subsets: ["latin"],
});

const playwrite = Playwrite_DE_Grund_Guides({
  variable: "--font-playwrite",
  weight: "400",
  fallback: ["cursive", "serif"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${plaster.variable} ${playwrite.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
